### ISSUE TITLE
Variables referencing another variable seem to not be working

### ISSUE THREAD

**Issue by mrlesmithjr** [cidrblock/td4a#2]
When defining a variable which in turn is a lookup of another variable seems to not be working correctly. Below is an example:

`DATA`:

```yaml
---
# defaults file for ansible-apache2

# Defines if Apache2 should be configured
apache2_config: false

# Defines if php.ini should be configured for Apache2
apache2_config_php: false

# Defines if Apache2 virtual hosts should be configured
apache2_config_virtual_hosts: true

# Defines Apache2 default listen port
apache2_default_port: 80

# Defines if php-sqlite should be installed
apache2_install_php_sqlite: false

# Defines if php should be installed
apache2_install_php: false

apache2_php_max_execution_time: 30

apache2_php_max_input_time: 60

# Defines max memory for Apache php
# default is 128M
apache2_php_max_memory: 128M

apache2_php_post_max_size: 8M

apache2_php_timezone: "UTC"

apache2_php_upload_max_filesize: 2M

apache2_server_admin: webmaster@localhost

# Define Apache2 virtual hosts
apache2_virtual_hosts:
 - documentroot: '/var/www/example.com'
   default_site: false
   port: 80
   serveradmin: '{{ apache2_server_admin }}'
   servername: 'www.example.com'
 - documentroot: '/var/www/example.org'
   default_site: false
   port: 80
   serveradmin: '{{ apache2_server_admin }}'
   servername: 'www.example.org'
 - documentroot: '/var/www/html'
   default_site: true
   port: 80
   serveradmin: '{{ apache2_server_admin }}'
   servername: ''

apache2_web_root: /var/www/html
apache2_log_dir: /var/log/apache

testVar: testing

anotherTestVar: "{{ testVar }}"
```

`TEMPLATE`:

```
{% if not apache2_config_virtual_hosts %}
<VirtualHost *:{{ apache2_default_port }}>
	ServerAdmin {{ apache2_server_admin }}
	DocumentRoot {{ apache2_web_root }}
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
{% elif apache2_virtual_hosts is defined and apache2_config_virtual_hosts %}
{%   for item in apache2_virtual_hosts %}
<VirtualHost *:{{ item.port }}>
	ServerAdmin {{ item.serveradmin }}
	DocumentRoot {{ item.documentroot }}
{%     if not item.default_site %}
	ServerName {{ item.servername }}
{%     endif %}
{%     if not item.default_site %}
	ErrorLog {{ apache2_log_dir }}/{{ item.servername }}_error.log
	CustomLog {{ apache2_log_dir }}/{{ item.servername }}_access.log combined
{%     elif item.default_site %}
ErrorLog {{ apache2_log_dir }}/error.log
CustomLog {{ apache2_log_dir }}/access.log combined
{%     endif %}

</VirtualHost>
{%   endfor %}
{% endif %}

{{ anotherTestVar }}
```

`RESULT`:

```
<VirtualHost *:80>
	ServerAdmin {{ apache2_server_admin }}
	DocumentRoot /var/www/example.com
	ServerName www.example.com
	ErrorLog /var/log/apache/www.example.com_error.log
	CustomLog /var/log/apache/www.example.com_access.log combined

</VirtualHost>
<VirtualHost *:80>
	ServerAdmin {{ apache2_server_admin }}
	DocumentRoot /var/www/example.org
	ServerName www.example.org
	ErrorLog /var/log/apache/www.example.org_error.log
	CustomLog /var/log/apache/www.example.org_access.log combined

</VirtualHost>
<VirtualHost *:80>
	ServerAdmin {{ apache2_server_admin }}
	DocumentRoot /var/www/html
ErrorLog /var/log/apache/error.log
CustomLog /var/log/apache/access.log combined

</VirtualHost>

{{ testVar }}
```

As you can see from the above example when defining the following:
```yaml
apache2_server_admin: webmaster@localhost

apache2_virtual_hosts:
 - documentroot: '/var/www/example.com'
   default_site: false
   port: 80
   serveradmin: '{{ apache2_server_admin }}'
   servername: 'www.example.com'
 - documentroot: '/var/www/example.org'
   default_site: false
   port: 80
   serveradmin: '{{ apache2_server_admin }}'
   servername: 'www.example.org'
 - documentroot: '/var/www/html'
   default_site: true
   port: 80
   serveradmin: '{{ apache2_server_admin }}'
   servername: ''
```
The result is not converting the `{{ apache2_server_admin }}` properly.

I also added the following to represent better:

```yaml
testVar: testing
anotherTestVar: "{{ testVar }}"
```

Which is being converted as `{{ testVar }}` rather than `testing`.
